### ISSUE TITLE
Nightly Builds: "Error Download of update package failed."

### ISSUE THREAD

**Issue by ghost** [joomla/developer.joomla.org#12]
Latest Update doesn't work, after click on "Reinstall Joomla core files":
![bildschirmfoto 2017-05-23 um 06 41 39](https://cloud.githubusercontent.com/assets/8235763/26338766/15ffc074-3f83-11e7-90d9-ed6ec3f9182e.JPG)
### System information
3.7.2-dev
macOS Sierra, 10.12.4
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by ghost** [comment]
Solution was to download and install Joomla_3.7.2_to_3.7.3-dev-Development-Patch_Package.zip.

**Comment by mbabker** [comment]
@zero-24 if the nightly build update server is using the patch package, that probably needs to change to use the update package to match the production update server.

**Comment by zero-24** [comment]
@franz-wohlkoenig which update server do you use?

**Comment by zero-24** [comment]
On the next patch update server we use: https://developer.joomla.org/nightlies/Joomla_3.7.3-dev-Development-Update_Package.zip which is a working URL / package download.

**Comment by zero-24** [comment]
Update & reinstall works for me? So I can not reproduce the issue.

**Comment by ghost** [comment]
@zero-24 Custom URL: https://update.joomla.org/core/nightlies/next_minor_list.xml

**Comment by zero-24** [comment]
This way you update to 3.8? Is this expected?

**Comment by ghost** [comment]
Update on 3.7.3-dev was 11 Hours ago. I updated by downloading and installing Nightly Build to 3.7.3-dev. Later i got Message to update on 3.8.

**Comment by zero-24** [comment]
this update server point to 3.8. since the 3.7.0 release, So if you need 3.7.3-dev you need to switch to next_patch_list.xml ;)

**Comment by ghost** [comment]
Haven't noticed changed URL, now got it. Thanks @zero-24
