### ISSUE TITLE
Correction in "suggested Roadmap"

### ISSUE THREAD

**Issue by ghost** [joomla/developer.joomla.org#2]
in [developer.joomla.org](https://developer.joomla.org/cms/roadmap.html) is Focus on "New Router", which is now wrong:
![bildschirmfoto 2017-03-24 um 14 40 39](https://cloud.githubusercontent.com/assets/8235763/24296630/22773d6c-10a0-11e7-9bf3-c1d3f43913c4.JPG)

**Comment by mbabker** [comment]
We're working on it.

https://github.com/joomla/joomla-websites/issues/897
