### ISSUE TITLE
Need more color codes for charts

### ISSUE THREAD

**Issue by mbabker** [joomla/developer.joomla.org#20]
https://github.com/joomla/developer.joomla.org/blob/master/modules/mod_joomladata/helper.php#L24

We have 16 hex codes right now.  The version chart has 44 entries (granted most of them not visible, but still assigned a color).  We probably should add a few to this list.

**Comment by ghost** [comment]
can we give each Version and Subversions its own Color(-Opacity) so its easier to "read"?

**Comment by mbabker** [comment]
Not without writing a module specific to each endpoint and hardcoding a list of color codes for each dataset.  Right now it's a generic module that just grabs a random unused value from the color list until the available color list is used up (when used up the tracking on used values is reset and it just keeps going).

**Comment by Sandra97** [comment]
I'll see to add more colors to the list today.

**Comment by ghost** [comment]
@mbabker sounds like to much work.

**Comment by Sandra97** [comment]
The 16 colours of the list are the official ones.
I can add some 'unofficial ones' (derivated from the official colours). 
![stats-colours](https://user-images.githubusercontent.com/4682328/31288243-789d0e3a-aa9a-11e7-8ae3-d0ff1400a00f.jpg)

**Comment by mbabker** [comment]
Seems fine to me.  The main point is to try and throw a few more color values into the chart so you don't have 3 of the same shade of blue next to each other (and it has happened).
