### ISSUE TITLE
"Custom URL" didn't work since 3.8.2-rc

### ISSUE THREAD

**Issue by ghost** [joomla/developer.joomla.org#22]
Since installing 3.8.2-rc got " No updates available." using Custom URL "https://update.joomla.org/core/nightlies/next_patch_list.xml".

**Comment by mbabker** [comment]
Expected.  `-dev` is a lower version than `-rc` and won't be offered as an update and we didn't go through the effort to change everything to use a version that would work for a couple days.

**Comment by ghost** [comment]
thanks for Info.
