### ISSUE TITLE
"Custom URL" didn't work since 3.8.3-dev

### ISSUE THREAD

**Issue by ghost** [joomla/developer.joomla.org#23]
Since installing 3.8.3-dev got " No updates available." using Custom URL "https://update.joomla.org/core/nightlies/next_patch_list.xml".

**Comment by mbabker** [comment]
@wilsonge or @rdeutz if you're around would you be able to update https://github.com/joomla/update.joomla.org/blob/master/www/core/nightlies/next_patch_extension.xml and https://github.com/joomla/update.joomla.org/blob/master/www/core/nightlies/next_patch_list.xml and push them to the update server?  My internet connection is complete garbage right now so I can't really do much.

**Comment by zero-24** [comment]
@rdeutz @wilsonge please check this one to be pushed to the update server: https://github.com/joomla/update.joomla.org/pull/80 I'm going to close this one than 😄
