### ISSUE TITLE
No actual Nightly Build

### ISSUE THREAD

**Issue by ghost** [joomla/developer.joomla.org#25]
Since 2 Days Builds are not updated:

![bildschirmfoto 2017-11-22 um 07 28 31](https://user-images.githubusercontent.com/8235763/33113116-f6ecc240-cf56-11e7-8aeb-d6d4951b8ea3.jpg)

**Comment by mbabker** [comment]
It's fine.  The job doesn't run if there are no changes detected to make a new build.
