### ISSUE TITLE
Feature Request: Show Summary of each Version at Usage Statics - Joomla! Version Stats

### ISSUE THREAD

**Issue by ghost** [joomla/developer.joomla.org#26]
Now its difficult to get Information about each Version. Example: You have to count 4 Subversions of 3.8:
![bildschirmfoto 2017-12-14 um 07 49 49](https://user-images.githubusercontent.com/8235763/33979215-a4859cb2-e0a3-11e7-88ef-5c8d70640a5d.jpg)

A Summery of Version 3.5, 3.6, 3.7, 3.8 near Diagram is useful.

**Comment by mbabker** [comment]
Changed the API for now to group results similar to other endpoints until the API endpoints are rewritten.
