### ISSUE TITLE
Warning: _deleteFolder You can't delete a base folder

### ISSUE THREAD

**Issue by todordev** [joomla/developer.joomla.org#28]
There was strange warning message when I opened that page.

https://developer.joomla.org/coding-standards.html

![warning](https://user-images.githubusercontent.com/1272206/35882095-af3263b2-0b8b-11e8-978e-0b8e24107c30.png)

**Comment by mbabker** [comment]
It's a core issue if anything.  Probably concurrent cache operations trying to delete the same item.  Nothing specific to fix for this specific site.
