### ISSUE TITLE
Usage Statistics gone

### ISSUE THREAD

**Issue by ghost** [joomla/developer.joomla.org#41]
https://developer.joomla.org/about/stats.html shows no Usage Statistics.

**Comment by conconnl** [comment]
Thanks for notifying us.
Opening the statics address it shows a specific error, I will look at changing this:
https://developer.joomla.org/stats/

CC: @HLeithner

**Comment by HLeithner** [comment]
Thanks for report, fixed by george and me.

**Comment by ghost** [comment]
Thank you all.
